default: &default
  adapter: postgresql
  encoding: unicode
  username: accupy
  password: accupy
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch('RAILS_MAX_THREADS', 5) %>

development:
  <<: *default
  database: accupy_development

test:
  <<: *default
  database: accupy_test

production:
  <<: *default
  database: accupy_production
  password: <%= ENV['ACCUPY_DATABASE_PASSWORD'] %>
